apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-openshift-staging
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-staging
    server: https://kubernetes.default.svc
  project: demo
  source:
    path: environments/staging
    repoURL: https://github.com/datianshi/hello-openshift-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true