apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: openshift-hello-build-
spec:
  params:
  pipelineRef:
    name: openshift-helloworld-build
  workspaces:
    - name: source-workspace
      persistentVolumeClaim:
        claimName: openshift-hello-build-workspace
      subPath: source
    - name: gitops-workspace
      persistentVolumeClaim:
        claimName: openshift-hello-build-workspace
      subPath: gitops
    - name: gitops-gitsecret
      secret:
        secretName: git-ssh-credentials-hello-openshift-config