apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openshift-hello-prod-deploy-workspace
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce