---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: openshift-helloworld-prod-deploy
  namespace: demo-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
      description: The application git repository
      default: https://github.com/datianshi/hello-openshift
    - name: APP_MANIFESTS_GIT
      type: string
      description: The application manifests git repository
      default: git@github.com:datianshi/hello-openshift-config.git
    - name: GIT_TAG
      type: string
  workspaces:
  - name: source-workspace
  - name: gitops-workspace
  - name: gitops-gitsecret
  tasks:
  - name: source-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source-workspace
    params:
    - name: revision
      value: $(params.GIT_TAG)
    - name: url
      value: $(params.GIT_REPO)
  - name: build-image
    taskRef:
      name: s2i-go
      kind: ClusterTask
    runAfter:
    - source-clone
    params:
      - name: IMAGE
        value: "quay.io/mobb/openshift-hello:$(params.GIT_TAG)"
    workspaces:
    - name: source
      workspace: source-workspace
  - name: update-deployment
    runAfter:
    - build-image
    taskRef:
      name: git-update-deployment
    params:
    - name: GIT_REPOSITORY
      value: $(params.APP_MANIFESTS_GIT)
    - name: CURRENT_IMAGE
      value: "quay.io/mobb/openshift-hello:latest"
    - name: NEW_IMAGE
      value: "quay.io/mobb/openshift-hello:$(params.GIT_TAG)"
    - name: NEW_DIGEST
      value: "$(tasks.build-image.results.IMAGE_DIGEST)"
    - name: KUSTOMIZATION_PATH
      value: environments/production
    workspaces:
    - name: workspace 
      workspace: gitops-workspace
    - name: ssh-directory
      workspace: gitops-gitsecret