---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: hello-openshift-prod-deploy
  namespace: demo-pipeline
spec:
  params:
    - name: git-revision
    - name: git-tag
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: hello-openshift
        name: hello-openshift-$(uid)
      spec:
        params:
          - name: APP_NAME
            value: $(tt.params.git-repo-name)
          - name: GIT_REPO
            value: $(tt.params.git-repo-url)
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
          - name: GIT_TAG
            value: $(tt.params.git-tag) 
        pipelineRef:
          name: openshift-helloworld-build-prod-deploy
        workspaces:
        - name: source-workspace
          persistentVolumeClaim:
            claimName: openshift-hello-build-prod-deploy-workspace
          subPath: source
        - name: gitops-workspace
          persistentVolumeClaim:
            claimName: openshift-hello-build-prod-deploy-workspace
          subPath: gitops
        - name: gitops-gitsecret
          secret:
            secretName: git-ssh-credentials-hello-openshift-config
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: hello-openshift-prod-deploy
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: hello-openshift-prod-deploy
spec:
  serviceAccountName: pipeline
  triggers:
    - name: hello-openshift
      interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev
        params:
        - name: "eventTypes"
          value: ["create"]
      bindings:
        - ref: hello-openshift-prod-deploy
      template:
        ref: hello-openshift-prod-deploy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: hello-openshift-prod-deploy
  name: el-hello-openshift-prod-deploy
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-hello-openshift
    weight: 100
